<div class="footer">
    <div class="footer-content"></div>
    <div class="footer-container">
      <div class="footer-subscribe-contact"><div>Stay Updated</div>
        <button class="moreinfo2">Subscribe</button>
      </div>
      <div class="footer-subscribe-contact" style="margin-top: 0;"><div>Contact Me</div>
        <a href="mailto:folke.hermansen@earendilcapital.no"><button class="moreinfo2">Email</button></a>
      </div>
      <div class="footer-subscribe-contact" style="margin-top: 0;">
        <button onclick="gototop()" id="top-button">Back to top</button>
      </div>
    </div>
  </div>
  <script src="script.js"></script>