  <head>
    <title>Earendil Capital</title>
    <link rel="shortcut icon" href="Favicon/favicon.ico" />
    <link rel="icon" href="/Favicon/favicon.ico"/>
    <link rel="icon" type="image/png" href="/Favicon/favicon.ico" />
    <link rel="stylesheet" href="style.css" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="parallax.js-1.5.0/parallax.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="description" content="Earendil Capital AS is an investment company that exercises active ownership. This company is not listed on the Oslo Stock Exchange ">
    <meta name="keywords" content="Earendil Capital, Investing, LLC, Web Design, Valknut Design, Earendil Capital">
    <meta name="author" content="Folke Hermansen">
  </head>