      <div class="nav" id="navbar">
      <img
            src="Favicon/android-chrome-192x192.png"
            alt="logo of website"
            class="logo"
        />
        <a href="index.php" class="headerlogotext"
          >Earendil Capital</a>
        <ul class="menu">
          <li class="selected"><a href="index.php">Home</a></li>
          <li><a href="investing.php">Investing</a></li>
          <li><a href="blog.php">Blog</a></li>
          <div class="dropdown" style="float: right">
            <button class="dropbtn">&#9662</button>

            <div class="dropdown-content" id="ddc" style="right: 0">
              <a href="mental-models.php">Mental Models</a>
              <a href="miscelaneous.php">Miscelaneous</a>
              <a href="philosophy.php">Philosophy</a>
              <a href="politics.php">Politics</a>
              <a href="book-reviews.php">Book Reveiws</a>
              <a href="economics.php">Economics</a>
            </div>
          </div>
        </ul>


      </div>
                <input type="checkbox" id="active">
                <div class="containernavbar" id="containernavbar">
                <img
            src="Favicon/android-chrome-192x192.png"
            alt="logo of website"
            class="logo"
        />
        <a href="index.php" class="headerlogotext2"
          >Earendil Capital</a>
          <label for="active" class="menu-button" id="menuchange">
          <div class="menu-btn-burger">
          </div>
          
          </label>
          <ul class="menu-mobile">
            <li class="one"><a href="index.php">Home</a></li>
            <li class="two"><a href="investing.php">Investing</a></li>
            <li class="three"><a href="blog.php">Blog</a></li>
            <li class="four"><a href="mental-models.php">Mental Models</a></li>
            <li class="five"><a href="miscelaneous.php">Miscelaneous</a></li>
            <li class="six"><a href="philosophy.php">Philosophy</a></li>
            <li class="seven"><a href="politics.php">Politics</a></li>
            <li class="eight"><a href="book-reviews.php">Book Reveiws</a></li>
            <li class="nine"><a href="economics.php">Economics</a></li>
            
          </ul>
        </div>