  <div class="nav2" id="navbar">
  
      <img
            src="Favicon/android-chrome-192x192.png"
            alt="logo of website"
            class="logo"
        />
        <a href="index.php" class="headerlogotext"
          >Earendil Capital</a>
        <ul class="menu">
          <li class="selected"><a href="index.php">Home</a></li>
          <li><a href="investing.php">Investing</a></li>
          <li><a href="blog.php">Blog</a></li>
          <div class="dropdown" style="float: right">
            <button class="dropbtn">&#9662</button>

            <div class="dropdown-content" style="right: 0">
              <a href="mental-models.php">Mental Models</a>
              <a href="miscelaneous.php">Miscelaneous</a>
              <a href="philosophy.php">Philosophy</a>
              <a href="politics.php">Politics</a>
              <a href="book-reviews.php">Book Reveiws</a>
              <a href="economics.php">Economics</a>
            </div>
          </div>
        </ul>
        <input type="checkbox" id="active">
        <div class="containernavbar">
          <label for="active" class="menu-button"></label>
                          <img
            src="Favicon/android-chrome-192x192.png"
            alt="logo of website"
            class="logo"
        />
          <ul class="menu-mobile">
            <li><a href="index.php">Home</a></li>
            <li><a href="investing.php">Investing</a></li>
            <li><a href="blog.php">Blog</a></li>
            <li><a href="mental-models.php">Mental Models</a></li>
            <li><a href="miscelaneous.php">Miscelaneous</a></li>
            <li><a href="philosophy.php">Philosophy</a></li>
            <li><a href="politics.php">Politics</a></li>
            <li><a href="book-reviews.php">Book Reveiws</a></li>
            <li><a href="economics.php">Economics</a></li>
            
          </ul>
        </div>

      </div>